### PR TITLE
fix: use defineProperty for appending prop in `storeName`

### PR DESCRIPTION
**Pull request by Jack-Works**
close https://github.com/endojs/endo/issues/943

### CODE REVIEW

**Comment by mourner** [comment]
Can you please explain this in more detail? Why is this fix needed?

**Comment by Jack-Works** [comment]
> Can you please explain this in more detail? Why is this fix needed?

In a secured environment, all built-in prototypes are frozen, including Object.prototype.

image

In this case, `this.storedNames[key] = true` will throw if key is `isPrototypeOf` which is on the Object.prototype.

**Comment by antfu** [comment]
@Jack-Works Can you give permission for maintainers to edit this PR (here should be a check box on this page)? We can't rebase this PR to the latest branch.

**Comment by Jack-Works** [comment]
@antfu I didn't find that check box but I manually merge with the latest commit

**Pull request merged**
