### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by leoj3n**
Add note about new maintainer, add 1-line summary below title, explain why generate sourcemaps

image

### CODE REVIEW

**Comment by antfu** [comment]
Thank you. But I don't really think this is necessary, I am also not the sole maintainer of this project, I think GitHub's contribution graph and collaborator badge are enough for collaborators to be recognized.

Regarding the explanation of the source map, I think it's not our responsibility to explain it as ppl come to this project should already know what Sourcemap is. (Even if not, we have Google right?)

Thanks again for the contribution but sorry as I am going to close this.

**Comment by antfu** [comment]
I would respect how Rich describes this package. Make the original descriptions de-emphasized as a quote would feel too much to me. I am helping out the maintaince of this package along with the other maintainers, regardless the activeness. This by no mean I am take the lead of this project and should have my name on the readme.

In any other open source projects, I think collaborators should have the right to close a ticket solely on their own with a bit of explaination (note the closed status doesn't mean you can't continue the dicssion or even bring it back). Otherwise I don't see it would help to have multiple ppl to vote to close one, giving there are already a lot of tasks that minatainers need to deal with daily.

About the explaintation of source map, I think having a PR that make `sourcemap` a link could be a good thing to have. It's hard to explaining it well within the limited space of README, so I would think it's out-of-scope of this project - or do you think we should explain what is JavaScript?

There are quite a few good resources out there to help you learn those technics. I don't think it's that hard for a developer to find what they want to learn.

**Comment by leoj3n** [comment]
I've opened a new PR adding a link for `sourcemap`.

While I expected push back on the mention and I tried to respect the original description, I didn't expect the 1-line summary and explanation of why it is important to generate a sourcemap to be closed without discussion or suggestions of how to better organize which is why I was giving you a hard time.

I still think an explanation along the lines of this is short and simple and eliminates confusion for anyone wondering why magic-string is used in, for example, many rollup plugins:

```md
## Why generate sourcemaps?

The [sourcemaps](https://docs.google.com/document/d/1U1RGAehQwRypUTovF1KRlpiOFze0b-_2gc6fAH0KY0k/edit) generated by magic-string avoids a break in the step debugger when doing string manipulations on a generated file.

For example, CLI tools like [Vite](https://vitejs.dev/) and [rollup](https://rollupjs.org/) allow users to write plugins that transform JavaScript files as part of a pipeline... If a generated file throws an error in the browser context, it helps with debugging if that error can be mapped back to the plugin line of code responsible.
```

While I understand it is a general purpose library, I am assuming that rollup plugins is where it used most. Perhaps it could be worded differently by someone more experienced, but I still stand by my original suggestion of adding to the readme in this way, regardless of where in the readme you want to put it.

**Comment by leoj3n** [comment]
Perhaps I should have elaborated more in the original comment...

In retrospect, it is clear to me now what a sourcemap is and why my rollup plugin should return a sourcemap along with the transformed code... However that was not the case when I encountered magic-string in the example plugin repos, which is what forced me to face sourcemaps and triggered my initial ignorance, which is why I ended up here.

The whole concept was foreign to me from the angle I was coming from... "Why not just use JavaScript string replace?"

You already being familiar with the concepts would not have these dumb questions. In retrospect it *is* really dumb, but I'm sure there are others out there that don't make the mental jump either when encountering these concepts for the first time.

I think this is also a hole in the vite/rollup documentation, and perhaps the repo with the plugins as well.

I did google things like "rollup sourcemap" and "vite sourcemap" but those results were not helpful in understanding what the sourcemap actually was and why it was needed in the rollup plugin. Searching for "what is a sourcemap" does yield decent results like you said, but for whatever reason it was still difficult to connect the dots when I first had the query.

In addition to the explanation I suggested here, I think the rollup docs could also use a paragraph or even a page explaining the whole sourcemap concept. I know it's really a basic concept, but not when you're totally ignorant of it.

If no additions get made to this repo's readme, hopefully this PR is still found by those that had questions like me. I think some explanation added to the otherwise very terse rollup or even vite docs would be good enough, but would also be great to have an explanation here as well, but alas I know you are busy and would rather just leave the readme alone.

If you know there are docs that have to do with this in either of those orgs please do link me to them! I may eventually make a suggestion to add some docs about this over there as I can't seem to find any good explanations otherwise.

**Pull request closed without merging**
